//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeerCopyWPF.Strings.en_US {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeerCopyWPF.Strings.en_US.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Use arrow keys to resize selection ähnelt.
        /// </summary>
        public static string ArrowKeysLblStr {
            get {
                return ResourceManager.GetString("ArrowKeysLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Toggle border on/off ähnelt.
        /// </summary>
        public static string BorderLblStr {
            get {
                return ResourceManager.GetString("BorderLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAPTURE OPTIONS ähnelt.
        /// </summary>
        public static string CaptureOptionsStr {
            get {
                return ResourceManager.GetString("CaptureOptionsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Clear selection ähnelt.
        /// </summary>
        public static string ClearLblStr {
            get {
                return ResourceManager.GetString("ClearLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Copy selection to clipboard ähnelt.
        /// </summary>
        public static string CopyLblStr {
            get {
                return ResourceManager.GetString("CopyLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Edit selection with default editor ähnelt.
        /// </summary>
        public static string EditLblStr {
            get {
                return ResourceManager.GetString("EditLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string MenuAboutStr {
            get {
                return ResourceManager.GetString("MenuAboutStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string MenuExitStr {
            get {
                return ResourceManager.GetString("MenuExitStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string MenuFileStr {
            get {
                return ResourceManager.GetString("MenuFileStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string MenuSettingsStr {
            get {
                return ResourceManager.GetString("MenuSettingsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Quit Selection ähnelt.
        /// </summary>
        public static string QuitLblStr {
            get {
                return ResourceManager.GetString("QuitLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Save selection to file ähnelt.
        /// </summary>
        public static string SaveLblStr {
            get {
                return ResourceManager.GetString("SaveLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Select entire screen ähnelt.
        /// </summary>
        public static string SelectAllLblStr {
            get {
                return ResourceManager.GetString("SelectAllLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection Capture ähnelt.
        /// </summary>
        public static string SelectCaptureBtnStr {
            get {
                return ResourceManager.GetString("SelectCaptureBtnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Area of Screen to Capture ähnelt.
        /// </summary>
        public static string SelectCaptureBtnTooltipStr {
            get {
                return ResourceManager.GetString("SelectCaptureBtnTooltipStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection Border Color ähnelt.
        /// </summary>
        public static string SettingsBorderColorStr {
            get {
                return ResourceManager.GetString("SettingsBorderColorStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Border ähnelt.
        /// </summary>
        public static string SettingsBorderKeyStr {
            get {
                return ResourceManager.GetString("SettingsBorderKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection Border Visible ähnelt.
        /// </summary>
        public static string SettingsBorderVisStr {
            get {
                return ResourceManager.GetString("SettingsBorderVisStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        public static string SettingsClearKeyStr {
            get {
                return ResourceManager.GetString("SettingsClearKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color ähnelt.
        /// </summary>
        public static string SettingsColorStr {
            get {
                return ResourceManager.GetString("SettingsColorStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string SettingsCopyKeyStr {
            get {
                return ResourceManager.GetString("SettingsCopyKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string SettingsEditKeyStr {
            get {
                return ResourceManager.GetString("SettingsEditKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default File Ext ähnelt.
        /// </summary>
        public static string SettingsFileExtStr {
            get {
                return ResourceManager.GetString("SettingsFileExtStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default File Name ähnelt.
        /// </summary>
        public static string SettingsFileNameStr {
            get {
                return ResourceManager.GetString("SettingsFileNameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key Bindings ähnelt.
        /// </summary>
        public static string SettingsKeyBindingsStr {
            get {
                return ResourceManager.GetString("SettingsKeyBindingsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc ähnelt.
        /// </summary>
        public static string SettingsMiscStr {
            get {
                return ResourceManager.GetString("SettingsMiscStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Settings ähnelt.
        /// </summary>
        public static string SettingsOpenSettingsKeyStr {
            get {
                return ResourceManager.GetString("SettingsOpenSettingsKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        public static string SettingsQuitKeyStr {
            get {
                return ResourceManager.GetString("SettingsQuitKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string SettingsSaveKeyStr {
            get {
                return ResourceManager.GetString("SettingsSaveKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        public static string SettingsSelectAllKeyStr {
            get {
                return ResourceManager.GetString("SettingsSelectAllKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch Screens ähnelt.
        /// </summary>
        public static string SettingsSwtchScrnKeyStr {
            get {
                return ResourceManager.GetString("SettingsSwtchScrnKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Tips ähnelt.
        /// </summary>
        public static string SettingsTipsKeyStr {
            get {
                return ResourceManager.GetString("SettingsTipsKeyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tips Visible ähnelt.
        /// </summary>
        public static string SettingsTipsVisStr {
            get {
                return ResourceManager.GetString("SettingsTipsVisStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Open settings ähnelt.
        /// </summary>
        public static string SettingsWinLblStr {
            get {
                return ResourceManager.GetString("SettingsWinLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection Window Opacity ähnelt.
        /// </summary>
        public static string SettingsWinOpacityStr {
            get {
                return ResourceManager.GetString("SettingsWinOpacityStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Switch screens ähnelt.
        /// </summary>
        public static string SwitchLblStr {
            get {
                return ResourceManager.GetString("SwitchLblStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Toggle tips on/off ähnelt.
        /// </summary>
        public static string TipsLblStr {
            get {
                return ResourceManager.GetString("TipsLblStr", resourceCulture);
            }
        }
    }
}
