//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgurSniper.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImgurSniper.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click or Press  ähnelt.
        /// </summary>
        public static string clickorpress {
            get {
                return ResourceManager.GetString("clickorpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ffmpeg.exe failed to convert MP4 to GIF! ähnelt.
        /// </summary>
        public static string couldNotCreateGif {
            get {
                return ResourceManager.GetString("couldNotCreateGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find FFmpegManager.exe! ähnelt.
        /// </summary>
        public static string couldNotFindFfmpeg {
            get {
                return ResourceManager.GetString("couldNotFindFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not install ffmpeg.exe! ähnelt.
        /// </summary>
        public static string couldNotInstallFfmpeg {
            get {
                return ResourceManager.GetString("couldNotInstallFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ffmpeg.exe could not start screen recording! ähnelt.
        /// </summary>
        public static string couldNotStartFfmpeg {
            get {
                return ResourceManager.GetString("couldNotStartFfmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not begin recording GIF! ähnelt.
        /// </summary>
        public static string couldNotStartRecording {
            get {
                return ResourceManager.GetString("couldNotStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ctrl + Shift + {0} ähnelt.
        /// </summary>
        public static string ctrlShiftShortcut {
            get {
                return ResourceManager.GetString("ctrlShiftShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown Error occured in ImgurSniper!
        ///ImgurSniper has to shut down!
        ///Would you like to see a detailed Exception Info? ({0}) ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error uploading File(s), make sure to check your Internet connection and see if the File is a valid Image file! ähnelt.
        /// </summary>
        public static string errorInstantUpload {
            get {
                return ResourceManager.GetString("errorInstantUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown Error occured! ähnelt.
        /// </summary>
        public static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FFmpeg encountered an unexpected Error!
        ///Do you want to see the FFmpeg Log? ähnelt.
        /// </summary>
        public static string ffmpegError {
            get {
                return ResourceManager.GetString("ffmpegError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GIF ähnelt.
        /// </summary>
        public static string gif {
            get {
                return ResourceManager.GetString("gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GIF was copied to your Clipboard! ähnelt.
        /// </summary>
        public static string gifCopyClipboard {
            get {
                return ResourceManager.GetString("gifCopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GIF was copied to your Clipboard and saved to file! ähnelt.
        /// </summary>
        public static string gifCopyClipboardSaved {
            get {
                return ResourceManager.GetString("gifCopyClipboardSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image was copied to your Clipboard! ähnelt.
        /// </summary>
        public static string imgCopyClipboard {
            get {
                return ResourceManager.GetString("imgCopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image was copied to your Clipboard and saved to file! ähnelt.
        /// </summary>
        public static string imgCopyClipboardSaved {
            get {
                return ResourceManager.GetString("imgCopyClipboardSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Image Width and/or Height is too small! ähnelt.
        /// </summary>
        public static string imgSize {
            get {
                return ResourceManager.GetString("imgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Size exceeds 12 MB! (Try smaller Images or use .JPEG!) ähnelt.
        /// </summary>
        public static string imgTooBig {
            get {
                return ResourceManager.GetString("imgTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GIF Size exceeds 12 MB! (Try smaller/shorter GIFs!) ähnelt.
        /// </summary>
        public static string imgTooBigGif {
            get {
                return ResourceManager.GetString("imgTooBigGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link to the Imgur Album has been copied to your Clipboard! ähnelt.
        /// </summary>
        public static string linkAlbumClipboard {
            get {
                return ResourceManager.GetString("linkAlbumClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link to Imgur has been copied to your Clipboard! ähnelt.
        /// </summary>
        public static string linkclipboard {
            get {
                return ResourceManager.GetString("linkclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link to Imgur has been copied to your Clipboard and saved to file! ähnelt.
        /// </summary>
        public static string linkclipboardAndSaved {
            get {
                return ResourceManager.GetString("linkclipboardAndSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging into Imgur Account... ähnelt.
        /// </summary>
        public static string loggingIn {
            get {
                return ResourceManager.GetString("loggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message: {0}
        ///
        /// ähnelt.
        /// </summary>
        public static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The File you selected is not a valid Image File! ähnelt.
        /// </summary>
        public static string notAnImage {
            get {
                return ResourceManager.GetString("notAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown Error occured! (Show this to the Smart Computer Apes: {0}) ähnelt.
        /// </summary>
        public static string otherErrorMsg {
            get {
                return ResourceManager.GetString("otherErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the Print Key ähnelt.
        /// </summary>
        public static string printKeyShortcut {
            get {
                return ResourceManager.GetString("printKeyShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image was saved to file! ähnelt.
        /// </summary>
        public static string savedToFile {
            get {
                return ResourceManager.GetString("savedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  to Snipe a new Image ähnelt.
        /// </summary>
        public static string toSnipeNew {
            get {
                return ResourceManager.GetString("toSnipeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh no! Sorry about that, it seems like ImgurSniper ran into an unexpected Error!
        ///But no worries, you can help out and get this Problem fixed asap!
        ///Do you want to help out and submit a ticket?
        ///(If you click yes, a new Browser Window opens) ähnelt.
        /// </summary>
        public static string unhandledError {
            get {
                return ResourceManager.GetString("unhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown Error occured in ImgurSniper.
        ///Error Message: &quot;{0}&quot;
        ///
        ///Do you want to restart ImgurSniper? ähnelt.
        /// </summary>
        public static string unhandledErrorDescription {
            get {
                return ResourceManager.GetString("unhandledErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading Image... ({0} KB) ähnelt.
        /// </summary>
        public static string uploading {
            get {
                return ResourceManager.GetString("uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error uploading Image to Imgur! ({0}) ähnelt.
        /// </summary>
        public static string uploadingError {
            get {
                return ResourceManager.GetString("uploadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error creating GIF! ({0}) ähnelt.
        /// </summary>
        public static string uploadingErrorGif {
            get {
                return ResourceManager.GetString("uploadingErrorGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading Image... ({0} KB) ({1} of {2}) ähnelt.
        /// </summary>
        public static string uploadingFiles {
            get {
                return ResourceManager.GetString("uploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading GIF... ({0} KB) ähnelt.
        /// </summary>
        public static string uploadingGif {
            get {
                return ResourceManager.GetString("uploadingGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploaded with ImgurSniper ähnelt.
        /// </summary>
        public static string uploadTitle {
            get {
                return ResourceManager.GetString("uploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whoops, something went wrong! ähnelt.
        /// </summary>
        public static string whoops {
            get {
                return ResourceManager.GetString("whoops", resourceCulture);
            }
        }
    }
}
