//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgurSniper.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImgurSniper.UI.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After Snapping... ähnelt.
        /// </summary>
        public static string afterSnapping {
            get {
                return ResourceManager.GetString("afterSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On all Monitors ähnelt.
        /// </summary>
        public static string allMonitor {
            get {
                return ResourceManager.GetString("allMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Settings were applied! ähnelt.
        /// </summary>
        public static string applied {
            get {
                return ResourceManager.GetString("applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically search for Updates ähnelt.
        /// </summary>
        public static string autoUpdate {
            get {
                return ResourceManager.GetString("autoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically upload to Imgur ähnelt.
        /// </summary>
        public static string autoUploadImgur {
            get {
                return ResourceManager.GetString("autoUploadImgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking for Updates... ähnelt.
        /// </summary>
        public static string checkingUpdate {
            get {
                return ResourceManager.GetString("checkingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Commits on GitHub ähnelt.
        /// </summary>
        public static string commitsDisplay {
            get {
                return ResourceManager.GetString("commitsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connecting to Imgur... ähnelt.
        /// </summary>
        public static string contactImgur {
            get {
                return ResourceManager.GetString("contactImgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context Menu ähnelt.
        /// </summary>
        public static string contextMenu {
            get {
                return ResourceManager.GetString("contextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right click any File in Windows Explorer (or on your Desktop) to open the Context Menu. To quickly upload any File to Imgur, you can now click &quot;Upload to Imgur&quot; ähnelt.
        /// </summary>
        public static string contextMenuDesc {
            get {
                return ResourceManager.GetString("contextMenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Image to Clipboard ähnelt.
        /// </summary>
        public static string copyClipboard {
            get {
                return ResourceManager.GetString("copyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not apply changes! ähnelt.
        /// </summary>
        public static string couldNotApply {
            get {
                return ResourceManager.GetString("couldNotApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not download ZIP Archive from github.com! ähnelt.
        /// </summary>
        public static string couldNotDownload {
            get {
                return ResourceManager.GetString("couldNotDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load Config! ähnelt.
        /// </summary>
        public static string couldNotLoad {
            get {
                return ResourceManager.GetString("couldNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ctrl + Shift +  ähnelt.
        /// </summary>
        public static string ctrlShift {
            get {
                return ResourceManager.GetString("ctrlShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On current Monitor ähnelt.
        /// </summary>
        public static string curMonitor {
            get {
                return ResourceManager.GetString("curMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to disable the ImgurSniper Tray Service? ähnelt.
        /// </summary>
        public static string disablingTrayWarning {
            get {
                return ResourceManager.GetString("disablingTrayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do nothing ähnelt.
        /// </summary>
        public static string doNothing {
            get {
                return ResourceManager.GetString("doNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading from github.com/mrousavy/ImgurSniper... ähnelt.
        /// </summary>
        public static string downloadingGitHub {
            get {
                return ResourceManager.GetString("downloadingGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading Update.. ähnelt.
        /// </summary>
        public static string downloadingUpdate {
            get {
                return ResourceManager.GetString("downloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Magnifying Glass ähnelt.
        /// </summary>
        public static string enMagnifying {
            get {
                return ResourceManager.GetString("enMagnifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading Config!
        ///(&quot;{0}&quot;) ähnelt.
        /// </summary>
        public static string errorConfig {
            get {
                return ResourceManager.GetString("errorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not retrieve Version/Update info from GitHub! ähnelt.
        /// </summary>
        public static string failedUpdate {
            get {
                return ResourceManager.GetString("failedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freeze Screen ähnelt.
        /// </summary>
        public static string freezeScreen {
            get {
                return ResourceManager.GetString("freezeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use this option if you want to pause the screen as soon as you open up ImgurSniper,
        ///e.g. for screenshotting elements that disappear once you open ImgurSniper. ähnelt.
        /// </summary>
        public static string freezeScreenTooltip {
            get {
                return ResourceManager.GetString("freezeScreenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GIF ähnelt.
        /// </summary>
        public static string gif {
            get {
                return ResourceManager.GetString("gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FPS: ähnelt.
        /// </summary>
        public static string gifFps {
            get {
                return ResourceManager.GetString("gifFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} FPS ähnelt.
        /// </summary>
        public static string gifFpsVal {
            get {
                return ResourceManager.GetString("gifFpsVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. Length: ähnelt.
        /// </summary>
        public static string gifLength {
            get {
                return ResourceManager.GetString("gifLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ∞ ähnelt.
        /// </summary>
        public static string gifLengthUnlimited {
            get {
                return ResourceManager.GetString("gifLengthUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Seconds ähnelt.
        /// </summary>
        public static string gifLengthVal {
            get {
                return ResourceManager.GetString("gifLengthVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkey (GIF): ähnelt.
        /// </summary>
        public static string hotkeyGif {
            get {
                return ResourceManager.GetString("hotkeyGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkey (Image): ähnelt.
        /// </summary>
        public static string hotkeyImg {
            get {
                return ResourceManager.GetString("hotkeyImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image ähnelt.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format: ähnelt.
        /// </summary>
        public static string imgFormat {
            get {
                return ResourceManager.GetString("imgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imgur Account ähnelt.
        /// </summary>
        public static string imgurAcc {
            get {
                return ResourceManager.GetString("imgurAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imgur Account (signed in as &quot;{0}&quot;) ähnelt.
        /// </summary>
        public static string imgurAccSignedIn {
            get {
                return ResourceManager.GetString("imgurAccSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error, ImgurSniper could not be found on your System! ähnelt.
        /// </summary>
        public static string imgurSniperNotFound {
            get {
                return ResourceManager.GetString("imgurSniperNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initializing... ähnelt.
        /// </summary>
        public static string initializing {
            get {
                return ResourceManager.GetString("initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language successfully changed, to proceed,
        ///you have to restart ImgurSniper.
        ///Do you want to restart ImgurSniper now? ähnelt.
        /// </summary>
        public static string langChanged {
            get {
                return ResourceManager.GetString("langChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Configuration... ähnelt.
        /// </summary>
        public static string loadConf {
            get {
                return ResourceManager.GetString("loadConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully logged in! Hi, {0}! ähnelt.
        /// </summary>
        public static string loggedIn {
            get {
                return ResourceManager.GetString("loggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snipe a Window on all connected Monitors (May be slower) ähnelt.
        /// </summary>
        public static string notOnlyMouse {
            get {
                return ResourceManager.GetString("notOnlyMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only Snipe a Window on the Monitor the Mouse Cursor is currently on. ähnelt.
        /// </summary>
        public static string onlyMouse {
            get {
                return ResourceManager.GetString("onlyMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Image in Browser after Upload ähnelt.
        /// </summary>
        public static string openBrowser {
            get {
                return ResourceManager.GetString("openBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Image in File Explorer after Snap ähnelt.
        /// </summary>
        public static string openFile {
            get {
                return ResourceManager.GetString("openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other... ähnelt.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clipboard ähnelt.
        /// </summary>
        public static string pageClipboard {
            get {
                return ResourceManager.GetString("pageClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die As soon as you have finished cropping the desired Rectangle, ImgurSniper will automatically copy the URL to Imgur or the whole Image itself (depending on your Settings) to your Clipboard, so you&apos;re ready to send it immediately! ähnelt.
        /// </summary>
        public static string pageClipboardDesc {
            get {
                return ResourceManager.GetString("pageClipboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw ähnelt.
        /// </summary>
        public static string pageDraw {
            get {
                return ResourceManager.GetString("pageDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Snipe Mode, you can draw on your screen to show the receiver something important (Circle, Arrows, ...), hide some Information, or show your drawing Skills!
        ///To enter the drawing Mode, you just need to press Space once in Snap Mode! ähnelt.
        /// </summary>
        public static string pageDrawDesc {
            get {
                return ResourceManager.GetString("pageDrawDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string pageGeneral {
            get {
                return ResourceManager.GetString("pageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ImgurSniper is an easy to use, fast and simple tool to help you share Images better.
        ///Open ImgurSniper with your Hotkey (default: Ctrl + Shift + X) and Crop an Image, or right click an Image File and click &quot;Upload to Imgur&quot; to upload the Image.
        ///See &quot;Snipe&quot; and &quot;Tray&quot; for more Information about the Program.
        ///
        ///Licensed under MIT Open Source License on github.com/mrousavy/ImgurSniper, you can modify the Program for your needs. To contribute, click the Fork button (top right) on GitHub, customize your Project, an [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string pageGeneralDesc {
            get {
                return ResourceManager.GetString("pageGeneralDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GIF ähnelt.
        /// </summary>
        public static string pageGif {
            get {
                return ResourceManager.GetString("pageGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To snipe a new GIF you have to press your GIF Hotkey (Default: Ctrl + Shift + G) or right-click the ImgurSniper Tray Icon (right side of your Taskbar) and hit &quot;GIF&quot;. Instead of sharing a single Image, you now can share a short Screen Recording!
        ///
        ///As soon as you selected your desired area, ImgurSniper will start recording the GIF. The blue Progress Bar below the grey Area will show you the Progress of the GIF (Once the Progress Bar is full, the screen recording will automatically stop and begin uploading the  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string pageGifDesc {
            get {
                return ResourceManager.GetString("pageGifDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string pagePrivacy {
            get {
                return ResourceManager.GetString("pagePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ImgurSniper does not collect any data, the only Information being uploaded is your Image. (The Image itself is private, and only accessible for users with the link.)
        ///As the ImgurSniper C# Project is on GitHub, you can easily view 100% of the Code.
        ///ImgurSniper uses OAuth2.0 for Authentication, so no Password or username will be stored, and you can revoke access anytime. ähnelt.
        /// </summary>
        public static string pagePrivacyDesc {
            get {
                return ResourceManager.GetString("pagePrivacyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right Click ähnelt.
        /// </summary>
        public static string pageRightClick {
            get {
                return ResourceManager.GetString("pageRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you Right Click with your Mouse in Snipe Mode, ImgurSniper will detect the Window you clicked, and upload the cropped Image of that Window to Imgur. ImgurSniper does detect a whole Window when you click the Titlebar and even Client Area(s) (Areas inside a Window). ähnelt.
        /// </summary>
        public static string pageRightClickDesc {
            get {
                return ResourceManager.GetString("pageRightClickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snipe ähnelt.
        /// </summary>
        public static string pageSnipe {
            get {
                return ResourceManager.GetString("pageSnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press your Hotkey (default: Ctrl + Shift + X) to open ImgurSniper in Snipe mode. In Snipe Mode, you can hold down your mouse and draw a Rectangle to select the Area you want to upload.
        ///Once you release the mouse, the Image will automatically be uploaded to Imgur (if enabled), saved as a file (optionally), and the Link (or Image itself) will be copied to your Clipboard. Depending on your Settings, the Image will be automatically opened for you to see aswell.
        ///Pro Tip: Hit Ctrl + A to instantly create a Screen [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string pageSnipeDesc {
            get {
                return ResourceManager.GetString("pageSnipeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tray ähnelt.
        /// </summary>
        public static string pageTray {
            get {
                return ResourceManager.GetString("pageTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Tray Service is running in the Background, so you can activate ImgurSniper with your Hotkey (default: Ctrl + Shift + X) way faster than launching the executable. The Tray Service is optimized to use as little processing power as possible, so your PC is definetly not slowed down. You can find the ImgurSniper Tray Program in the bottom right corner of your Screen, Right Click the Icon to open the Menu. ähnelt.
        /// </summary>
        public static string pageTrayDesc {
            get {
                return ResourceManager.GetString("pageTrayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path: ähnelt.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected Path does not exist! ähnelt.
        /// </summary>
        public static string pathNotExist {
            get {
                return ResourceManager.GetString("pathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the PIN you received on the Website. ähnelt.
        /// </summary>
        public static string plsPin {
            get {
                return ResourceManager.GetString("plsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press any Key...
        ///(ESC to cancel) ähnelt.
        /// </summary>
        public static string pressKey {
            get {
                return ResourceManager.GetString("pressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quality: ähnelt.
        /// </summary>
        public static string quality {
            get {
                return ResourceManager.GetString("quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repair ähnelt.
        /// </summary>
        public static string repair {
            get {
                return ResourceManager.GetString("repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repaired ImgurSniper. Please restart ImgurSniper to complete! ähnelt.
        /// </summary>
        public static string repairedImgurSniper {
            get {
                return ResourceManager.GetString("repairedImgurSniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save snapped Images locally ähnelt.
        /// </summary>
        public static string saveLocally {
            get {
                return ResourceManager.GetString("saveLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the Path where ImgurSniper should save Images. ähnelt.
        /// </summary>
        public static string selectPath {
            get {
                return ResourceManager.GetString("selectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capture ähnelt.
        /// </summary>
        public static string settingsCapture {
            get {
                return ResourceManager.GetString("settingsCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Events ähnelt.
        /// </summary>
        public static string settingsEvents {
            get {
                return ResourceManager.GetString("settingsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string settingsHome {
            get {
                return ResourceManager.GetString("settingsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imgur ähnelt.
        /// </summary>
        public static string settingsImgur {
            get {
                return ResourceManager.GetString("settingsImgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other ähnelt.
        /// </summary>
        public static string settingsOther {
            get {
                return ResourceManager.GetString("settingsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Mouse ähnelt.
        /// </summary>
        public static string showMouse {
            get {
                return ResourceManager.GetString("showMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in ähnelt.
        /// </summary>
        public static string singIn {
            get {
                return ResourceManager.GetString("singIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign out ähnelt.
        /// </summary>
        public static string singOut {
            get {
                return ResourceManager.GetString("singOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skip ähnelt.
        /// </summary>
        public static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skip these ImgurSniper Updates ähnelt.
        /// </summary>
        public static string skipTooltip {
            get {
                return ResourceManager.GetString("skipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snipe! ähnelt.
        /// </summary>
        public static string snipe {
            get {
                return ResourceManager.GetString("snipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imgur Sniper Settings ähnelt.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ImgurSniper Tray/Background Service ähnelt.
        /// </summary>
        public static string trayService {
            get {
                return ResourceManager.GetString("trayService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ImgurSniper Tray Service is not running! ähnelt.
        /// </summary>
        public static string trayServiceNotRunning {
            get {
                return ResourceManager.GetString("trayServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not start ImgurSniper tray service! ähnelt.
        /// </summary>
        public static string trayServiceStartFail {
            get {
                return ResourceManager.GetString("trayServiceStartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Troubleshooting ähnelt.
        /// </summary>
        public static string troubleshooting {
            get {
                return ResourceManager.GetString("troubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh no! It looks like you encountered an Error while uploading an Image.
        ///If this problem occurs more often, try the following:
        ///    • Try logging in with your Imgur Account
        ///    • Change the Image Format from .PNG to .JPEG
        ///    • Restart your Computer
        ///    • Make sure that you have Write Permissions to Documents/ImgurSniper
        ///    • Make sure that your GIF is not too long, too big, or has too many FPS!
        ///Does the Error still occur? Maybe your Internet Connection
        ///is too slow for the Imgur Service. ähnelt.
        /// </summary>
        public static string troubleshootingTips {
            get {
                return ResourceManager.GetString("troubleshootingTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh no! Sorry about that, it seems like ImgurSniper ran into an unexpected Error!
        ///But no worries, you can help out and get this Problem fixed asap!
        ///Do you want to help out and submit a ticket?
        ///(If you click yes, a new Browser Window opens) ähnelt.
        /// </summary>
        public static string unhandledError {
            get {
                return ResourceManager.GetString("unhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown Error occured in ImgurSniper.
        ///Error Message: &quot;{0}&quot;
        ///
        ///Do you want to restart ImgurSniper? ähnelt.
        /// </summary>
        public static string unhandledErrorDescription {
            get {
                return ResourceManager.GetString("unhandledErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown Error occured!\r\nShow this to the smart Computer apes: {0} ähnelt.
        /// </summary>
        public static string unknownError {
            get {
                return ResourceManager.GetString("unknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An ImgurSniper Update is available to download! (v{0}/{1}) ähnelt.
        /// </summary>
        public static string updateAvailable {
            get {
                return ResourceManager.GetString("updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last: {0} ähnelt.
        /// </summary>
        public static string updateLast {
            get {
                return ResourceManager.GetString("updateLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search now ähnelt.
        /// </summary>
        public static string updateNow {
            get {
                return ResourceManager.GetString("updateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use .JPEG for Images (Faster uploads, lower Quality) ähnelt.
        /// </summary>
        public static string useJPEG {
            get {
                return ResourceManager.GetString("useJPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use .PNG for Images (Slower uploads, higher Quality) ähnelt.
        /// </summary>
        public static string usePNG {
            get {
                return ResourceManager.GetString("usePNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Print Key as Shortcut ähnelt.
        /// </summary>
        public static string usePrint {
            get {
                return ResourceManager.GetString("usePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version Info ähnelt.
        /// </summary>
        public static string verInfo {
            get {
                return ResourceManager.GetString("verInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My Images ähnelt.
        /// </summary>
        public static string viewPics {
            get {
                return ResourceManager.GetString("viewPics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to apply the changes you made? ähnelt.
        /// </summary>
        public static string wantToApply {
            get {
                return ResourceManager.GetString("wantToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Where to snipe ähnelt.
        /// </summary>
        public static string whereSnipe {
            get {
                return ResourceManager.GetString("whereSnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong PIN? Could not login to Imgur! ({0}) ähnelt.
        /// </summary>
        public static string wrongPin {
            get {
                return ResourceManager.GetString("wrongPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
